### ISSUE TITLE
I want the links for OSTD movies and ground truth?

### ISSUE THREAD

**Issue by meisa233** [ICLR-2020-ILS-SUMM/ILS-SUMM#1]
From your paper, I see that there are links for OSTD movies and ground truth optimal total distance of all above datasets.
Can you update them?
Thank you.

**Comment by meisa233** [comment]
Can you release the optimal total distance of each video?
Thank you.

**Comment by ICLR-2020-ILS-SUMM** [comment]
Sure, I'm currently on vacation, but in a few days I'll be back and release OSTD ground truth.
Thanks for your patience.

**Comment by meisa233** [comment]
> Sure, I'm currently on vacation, but in a few days I'll be back and release OSTD ground truth.
> Thanks for your patience.

Thanks for your reply!
By the way, I have several problems.

From your paper, a method called KTS is used to detect shot boundary.
I have run its code, and I found that we need to set the number of shot, right?
How to set a proper value?

Besides, PuLP is used to obtain the ground truth. How do I use it to get GT?

**Comment by ICLR-2020-ILS-SUMM** [comment]
We released the [datasets](https://github.com/ICLR-2020-ILS-SUMM/ILS-SUMM/tree/master/datasets). It also contains a [description of the datasets and details about the shots segmentation and the way we used PuLP to obtain the GT](https://github.com/ICLR-2020-ILS-SUMM/ILS-SUMM/tree/master/datasets/Datasets%20Description.md).

**Comment by meisa233** [comment]
> We now released the [datasets](https://github.com/ICLR-2020-ILS-SUMM/ILS-SUMM/tree/master/datasets). It also contains a [description of the datasets and details about the shots segmentation and the way we used PuLP to obtain the GT](https://github.com/ICLR-2020-ILS-SUMM/ILS-SUMM/tree/master/datasets/Datasets%20Description.md).

Thank you!!!
