### ISSUE TITLE
how can i get custom video's shots_features.npy and shots_durations.npy?

### ISSUE THREAD

**Issue by junedgar** [ICLR-2020-ILS-SUMM/ILS-SUMM#2]
Thank you for your work!
I have some confuse to process the custom video,  is there a script to get the shots' features and durations directly?

**Comment by YairShemer** [comment]
Hi,
This repository had moved to [this location](https://github.com/YairShemer/ILS-SUMM).
Please see the answer to a similar issue [here](https://github.com/YairShemer/ILS-SUMM/issues/1). 
I hope it will help you.
For any further questions please open there a new issue.

**Comment by junedgar** [comment]
@YairShemer 
Thank you for your reply!
